/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IFlashLoanReceiverInterface extends ethers.utils.Interface {
  functions: {
    "executeOperation(address,uint256,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;

  events: {};
}

export class IFlashLoanReceiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IFlashLoanReceiverInterface;

  functions: {
    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  executeOperation(
    _reserve: string,
    _amount: BigNumberish,
    _fee: BigNumberish,
    _params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeOperation(address,uint256,uint256,bytes)"(
    _reserve: string,
    _amount: BigNumberish,
    _fee: BigNumberish,
    _params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
