/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILendingPoolAddressesProviderInterface
  extends ethers.utils.Interface {
  functions: {
    "getLendingPool()": FunctionFragment;
    "setLendingPoolImpl(address)": FunctionFragment;
    "getLendingPoolCore()": FunctionFragment;
    "setLendingPoolCoreImpl(address)": FunctionFragment;
    "getLendingPoolConfigurator()": FunctionFragment;
    "setLendingPoolConfiguratorImpl(address)": FunctionFragment;
    "getLendingPoolDataProvider()": FunctionFragment;
    "setLendingPoolDataProviderImpl(address)": FunctionFragment;
    "getLendingPoolParametersProvider()": FunctionFragment;
    "setLendingPoolParametersProviderImpl(address)": FunctionFragment;
    "getTokenDistributor()": FunctionFragment;
    "setTokenDistributor(address)": FunctionFragment;
    "getFeeProvider()": FunctionFragment;
    "setFeeProviderImpl(address)": FunctionFragment;
    "getLendingPoolLiquidationManager()": FunctionFragment;
    "setLendingPoolLiquidationManager(address)": FunctionFragment;
    "getLendingPoolManager()": FunctionFragment;
    "setLendingPoolManager(address)": FunctionFragment;
    "getPriceOracle()": FunctionFragment;
    "setPriceOracle(address)": FunctionFragment;
    "getLendingRateOracle()": FunctionFragment;
    "setLendingRateOracle(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolCoreImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolConfigurator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolConfiguratorImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolDataProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolDataProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolParametersProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolParametersProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenDistributor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolLiquidationManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolLiquidationManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingRateOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingRateOracle",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolCoreImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolConfiguratorImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolDataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolDataProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolParametersProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolParametersProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolLiquidationManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolLiquidationManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingRateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingRateOracle",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILendingPoolAddressesProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILendingPoolAddressesProviderInterface;

  functions: {
    getLendingPool(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPool()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolImpl(
      _pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolImpl(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolCore(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolCore()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolCoreImpl(address)"(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolConfigurator(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolConfigurator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolConfiguratorImpl(address)"(
      _configurator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolDataProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolDataProvider()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolDataProviderImpl(address)"(
      _provider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolParametersProvider()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolParametersProviderImpl(address)"(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getTokenDistributor(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getTokenDistributor()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setTokenDistributor(address)"(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getFeeProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getFeeProvider()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFeeProviderImpl(address)"(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolLiquidationManager()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolLiquidationManager(address)"(
      _manager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolManager(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingPoolManager()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingPoolManager(address)"(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPriceOracle(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getPriceOracle()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingRateOracle(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLendingRateOracle()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLendingRateOracle(address)"(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getLendingPool(overrides?: CallOverrides): Promise<string>;

  "getLendingPool()"(overrides?: CallOverrides): Promise<string>;

  setLendingPoolImpl(
    _pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolImpl(address)"(
    _pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolCore(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolCore()"(overrides?: CallOverrides): Promise<string>;

  setLendingPoolCoreImpl(
    _lendingPoolCore: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolCoreImpl(address)"(
    _lendingPoolCore: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolConfigurator(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolConfigurator()"(overrides?: CallOverrides): Promise<string>;

  setLendingPoolConfiguratorImpl(
    _configurator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolConfiguratorImpl(address)"(
    _configurator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolDataProvider(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolDataProvider()"(overrides?: CallOverrides): Promise<string>;

  setLendingPoolDataProviderImpl(
    _provider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolDataProviderImpl(address)"(
    _provider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolParametersProvider(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolParametersProvider()"(
    overrides?: CallOverrides
  ): Promise<string>;

  setLendingPoolParametersProviderImpl(
    _parametersProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolParametersProviderImpl(address)"(
    _parametersProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getTokenDistributor(overrides?: CallOverrides): Promise<string>;

  "getTokenDistributor()"(overrides?: CallOverrides): Promise<string>;

  setTokenDistributor(
    _tokenDistributor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setTokenDistributor(address)"(
    _tokenDistributor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getFeeProvider(overrides?: CallOverrides): Promise<string>;

  "getFeeProvider()"(overrides?: CallOverrides): Promise<string>;

  setFeeProviderImpl(
    _feeProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFeeProviderImpl(address)"(
    _feeProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolLiquidationManager(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolLiquidationManager()"(
    overrides?: CallOverrides
  ): Promise<string>;

  setLendingPoolLiquidationManager(
    _manager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolLiquidationManager(address)"(
    _manager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolManager(overrides?: CallOverrides): Promise<string>;

  "getLendingPoolManager()"(overrides?: CallOverrides): Promise<string>;

  setLendingPoolManager(
    _lendingPoolManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingPoolManager(address)"(
    _lendingPoolManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPriceOracle(overrides?: CallOverrides): Promise<string>;

  "getPriceOracle()"(overrides?: CallOverrides): Promise<string>;

  setPriceOracle(
    _priceOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPriceOracle(address)"(
    _priceOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingRateOracle(overrides?: CallOverrides): Promise<string>;

  "getLendingRateOracle()"(overrides?: CallOverrides): Promise<string>;

  setLendingRateOracle(
    _lendingRateOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLendingRateOracle(address)"(
    _lendingRateOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getLendingPool(overrides?: CallOverrides): Promise<string>;

    "getLendingPool()"(overrides?: CallOverrides): Promise<string>;

    setLendingPoolImpl(_pool: string, overrides?: CallOverrides): Promise<void>;

    "setLendingPoolImpl(address)"(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolCore(overrides?: CallOverrides): Promise<string>;

    "getLendingPoolCore()"(overrides?: CallOverrides): Promise<string>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolCoreImpl(address)"(
      _lendingPoolCore: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolConfigurator(overrides?: CallOverrides): Promise<string>;

    "getLendingPoolConfigurator()"(overrides?: CallOverrides): Promise<string>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolConfiguratorImpl(address)"(
      _configurator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolDataProvider(overrides?: CallOverrides): Promise<string>;

    "getLendingPoolDataProvider()"(overrides?: CallOverrides): Promise<string>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolDataProviderImpl(address)"(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<string>;

    "getLendingPoolParametersProvider()"(
      overrides?: CallOverrides
    ): Promise<string>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolParametersProviderImpl(address)"(
      _parametersProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getTokenDistributor(overrides?: CallOverrides): Promise<string>;

    "getTokenDistributor()"(overrides?: CallOverrides): Promise<string>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTokenDistributor(address)"(
      _tokenDistributor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getFeeProvider(overrides?: CallOverrides): Promise<string>;

    "getFeeProvider()"(overrides?: CallOverrides): Promise<string>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFeeProviderImpl(address)"(
      _feeProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<string>;

    "getLendingPoolLiquidationManager()"(
      overrides?: CallOverrides
    ): Promise<string>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolLiquidationManager(address)"(
      _manager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPoolManager(overrides?: CallOverrides): Promise<string>;

    "getLendingPoolManager()"(overrides?: CallOverrides): Promise<string>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingPoolManager(address)"(
      _lendingPoolManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getPriceOracle(overrides?: CallOverrides): Promise<string>;

    "getPriceOracle()"(overrides?: CallOverrides): Promise<string>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingRateOracle(overrides?: CallOverrides): Promise<string>;

    "getLendingRateOracle()"(overrides?: CallOverrides): Promise<string>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLendingRateOracle(address)"(
      _lendingRateOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLendingPool(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingPool()"(overrides?: CallOverrides): Promise<BigNumber>;

    setLendingPoolImpl(
      _pool: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolImpl(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolCore(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingPoolCore()"(overrides?: CallOverrides): Promise<BigNumber>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolCoreImpl(address)"(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolConfigurator(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingPoolConfigurator()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolConfiguratorImpl(address)"(
      _configurator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolDataProvider(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingPoolDataProvider()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolDataProviderImpl(address)"(
      _provider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLendingPoolParametersProvider()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolParametersProviderImpl(address)"(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getTokenDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    "getTokenDistributor()"(overrides?: CallOverrides): Promise<BigNumber>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setTokenDistributor(address)"(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getFeeProvider(overrides?: CallOverrides): Promise<BigNumber>;

    "getFeeProvider()"(overrides?: CallOverrides): Promise<BigNumber>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFeeProviderImpl(address)"(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLendingPoolLiquidationManager()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolLiquidationManager(address)"(
      _manager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingPoolManager(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingPoolManager()"(overrides?: CallOverrides): Promise<BigNumber>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingPoolManager(address)"(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getPriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    "getPriceOracle()"(overrides?: CallOverrides): Promise<BigNumber>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getLendingRateOracle(overrides?: CallOverrides): Promise<BigNumber>;

    "getLendingRateOracle()"(overrides?: CallOverrides): Promise<BigNumber>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLendingRateOracle(address)"(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLendingPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getLendingPool()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolImpl(
      _pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolImpl(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolCore(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolCore()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolCoreImpl(address)"(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolConfigurator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolConfigurator()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolConfiguratorImpl(address)"(
      _configurator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolDataProvider(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolDataProvider()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolDataProviderImpl(address)"(
      _provider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolParametersProvider()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolParametersProviderImpl(address)"(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getTokenDistributor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokenDistributor()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setTokenDistributor(address)"(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getFeeProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFeeProvider()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFeeProviderImpl(address)"(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolLiquidationManager()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolLiquidationManager(address)"(
      _manager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingPoolManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPoolManager()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingPoolManager(address)"(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getPriceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getPriceOracle()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getLendingRateOracle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingRateOracle()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLendingRateOracle(address)"(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
