/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILendingRateOracleInterface extends ethers.utils.Interface {
  functions: {
    "getMarketBorrowRate(address)": FunctionFragment;
    "setMarketBorrowRate(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMarketBorrowRate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketBorrowRate",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMarketBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketBorrowRate",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILendingRateOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILendingRateOracleInterface;

  functions: {
    /**
     * returns the market borrow rate in ray*
     */
    getMarketBorrowRate(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    /**
     * returns the market borrow rate in ray*
     */
    "getMarketBorrowRate(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    setMarketBorrowRate(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    "setMarketBorrowRate(address,uint256)"(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  /**
   * returns the market borrow rate in ray*
   */
  getMarketBorrowRate(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * returns the market borrow rate in ray*
   */
  "getMarketBorrowRate(address)"(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * sets the market borrow rate. Rate value must be in ray*
   */
  setMarketBorrowRate(
    _asset: string,
    _rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * sets the market borrow rate. Rate value must be in ray*
   */
  "setMarketBorrowRate(address,uint256)"(
    _asset: string,
    _rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * returns the market borrow rate in ray*
     */
    getMarketBorrowRate(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * returns the market borrow rate in ray*
     */
    "getMarketBorrowRate(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    setMarketBorrowRate(
      _asset: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    "setMarketBorrowRate(address,uint256)"(
      _asset: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    /**
     * returns the market borrow rate in ray*
     */
    getMarketBorrowRate(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * returns the market borrow rate in ray*
     */
    "getMarketBorrowRate(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    setMarketBorrowRate(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    "setMarketBorrowRate(address,uint256)"(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * returns the market borrow rate in ray*
     */
    getMarketBorrowRate(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * returns the market borrow rate in ray*
     */
    "getMarketBorrowRate(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    setMarketBorrowRate(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * sets the market borrow rate. Rate value must be in ray*
     */
    "setMarketBorrowRate(address,uint256)"(
      _asset: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
