/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPriceOracleInterface extends ethers.utils.Interface {
  functions: {
    "getAssetPrice(address)": FunctionFragment;
    "setAssetPrice(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAssetPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetPrice",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPriceOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPriceOracleInterface;

  functions: {
    /**
     * returns the asset price in ETH
     * *********
     */
    getAssetPrice(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    /**
     * returns the asset price in ETH
     * *********
     */
    "getAssetPrice(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    /**
     * sets the asset price, in wei
     * *********
     */
    setAssetPrice(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * sets the asset price, in wei
     * *********
     */
    "setAssetPrice(address,uint256)"(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  /**
   * returns the asset price in ETH
   * *********
   */
  getAssetPrice(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  /**
   * returns the asset price in ETH
   * *********
   */
  "getAssetPrice(address)"(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * sets the asset price, in wei
   * *********
   */
  setAssetPrice(
    _asset: string,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * sets the asset price, in wei
   * *********
   */
  "setAssetPrice(address,uint256)"(
    _asset: string,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * returns the asset price in ETH
     * *********
     */
    getAssetPrice(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * returns the asset price in ETH
     * *********
     */
    "getAssetPrice(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * sets the asset price, in wei
     * *********
     */
    setAssetPrice(
      _asset: string,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * sets the asset price, in wei
     * *********
     */
    "setAssetPrice(address,uint256)"(
      _asset: string,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    /**
     * returns the asset price in ETH
     * *********
     */
    getAssetPrice(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * returns the asset price in ETH
     * *********
     */
    "getAssetPrice(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * sets the asset price, in wei
     * *********
     */
    setAssetPrice(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * sets the asset price, in wei
     * *********
     */
    "setAssetPrice(address,uint256)"(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * returns the asset price in ETH
     * *********
     */
    getAssetPrice(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * returns the asset price in ETH
     * *********
     */
    "getAssetPrice(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * sets the asset price, in wei
     * *********
     */
    setAssetPrice(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * sets the asset price, in wei
     * *********
     */
    "setAssetPrice(address,uint256)"(
      _asset: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
